name: veronikaz
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2583354851230979
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#012191'
    - '#fdfdfd'
    - '#8faad7'
    - '#1f68d0'
    - '#535852'
  brandStrength: 0.625
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
